# Generated by Django 3.1 on 2020-08-20 22:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Foto principal')),
                ('link_mp', models.URLField(blank=True, null=True, verbose_name='Link a Mercado Pago')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Foto 1')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Foto 2')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'articulo',
                'verbose_name_plural': 'articulos',
                'ordering': ['-created'],
            },
        ),
    ]
